server:
  port: 8088

spring:
  application:
    name: terminal-service
  config:
    import:
      - nacos:terminal-service-dev.yml?group=DEFAULT_GROUP&fresh=true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.185:8848
        namespace: 9bc919e2-0ba2-40ed-9ad9-67c85d4cd5e0
        group: DEFAULT_GROUP
        username: Nan
        password: Nan12091209
        access-key: nan_nacos
        secret-key: nanproduced
        fail-fast: false
      config:
        server-addr: 192.168.1.185:8848
        namespace: 9bc919e2-0ba2-40ed-9ad9-67c85d4cd5e0
        group: DEFAULT_GROUP
        username: Nan
        password: Nan12091209
        access-key: nan_nacos
        secret-key: nanproduced
        timeout: 5000
        config-long-poll-timeout: 1000
        config-retry-time: 100000
        max-retry: 3
        refresh-enabled: true
        file-extension: yml