server:
  port: 8088

spring:
  application:
    name: terminal-service
  config:
    import:
      - nacos:terminal-service-intranet.yml?group=DEFAULT_GROUP&fresh=true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.51.114:8848
        service: terminal-service
        namespace: 500a59a2-cdc1-41f0-ae2e-5d4b1ed1e92f
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        register-enabled: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
      config:
        server-addr: 192.168.51.114:8848
        namespace: 500a59a2-cdc1-41f0-ae2e-5d4b1ed1e92f
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        timeout: 5000
        config-long-poll-timeout: 1000
        config-retry-time: 100000
        max-retry: 3
        refresh-enabled: true
        file-extension: yml