server:
  port: 8088

spring:
  application:
    name: terminal-service
  config:
    import:
      - nacos:terminal-service-intranet.yml?group=DEFAULT_GROUP&fresh=true
  cloud:
    nacos:
      discovery:
        enabled: false  # 禁用Spring Cloud Discovery注册
      config:
        server-addr: 192.168.51.114:8848
        namespace: bf06b404-e018-4549-987b-505386a734dc
        group: DEFAULT_GROUP
        username: nacos
        password: LedMasterNacos
        timeout: 5000
        config-long-poll-timeout: 1000
        config-retry-time: 100000
        max-retry: 3
        refresh-enabled: true
        file-extension: yml